version: '3.1'

services:

  redmine:
    image: redmine:3.4.2
    ports:
      - ${HTTP_PORT}:3000
    links:
      - db:db
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: "${REDMINE_DB_PASSWORD}"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${REDMINE_DB_PASSWORD}"
      MYSQL_DATABASE: redmine
